In [15]:
import os
os.chdir('/Users/anasantana/Desktop/copa')

import pandas as pd
import numpy as np
from datetime import date

In [16]:
results    = pd.read_csv('results.csv',      parse_dates=['date'])
shootouts  = pd.read_csv('shootouts.csv',    parse_dates=['date'])
fnames     = pd.read_csv('former_names.csv', parse_dates=['start_date', 'end_date'])

print(f'Results:   {len(results):,} matches')
print(f'Shootouts: {len(shootouts):,} matches')
print(f'Name mappings: {len(fnames)}')
results.head()

Results:   49,477 matches
Shootouts: 678 matches
Name mappings: 36

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [17]:
name_map = dict(zip(fnames['former'], fnames['current']))

def normalize_team(name):
    return name_map.get(name, name)

for col in ['home_team', 'away_team']:
    results[col]   = results[col].map(normalize_team)
    shootouts[col] = shootouts[col].map(normalize_team)
shootouts['winner'] = shootouts['winner'].map(normalize_team)

print('Team names normalized.')

Team names normalized.

In [18]:
shootouts_slim = shootouts[['date', 'home_team', 'away_team', 'winner']].rename(
    columns={'winner': 'shootout_winner'}
)

df = results.merge(shootouts_slim, on=['date', 'home_team', 'away_team'], how='left')

def true_winner(row):
    if pd.notna(row['shootout_winner']):
        return row['shootout_winner']
    elif row['home_score'] > row['away_score']:
        return row['home_team']
    elif row['away_score'] > row['home_score']:
        return row['away_team']
    else:
        return 'Draw'

df['winner'] = df.apply(true_winner, axis=1)

print(f'Matches with shootout data: {df["shootout_winner"].notna().sum()}')

Matches with shootout data: 677

In [19]:
wc2026_matches = df[
    (df['tournament'] == 'FIFA World Cup') & (df['date'].dt.year == 2026)
]

WC2026_TEAMS = set(
    wc2026_matches['home_team'].tolist() + wc2026_matches['away_team'].tolist()
)

print(f'WC 2026 teams found: {len(WC2026_TEAMS)}')
print(sorted(WC2026_TEAMS))

WC 2026 teams found: 48
['Algeria', 'Argentina', 'Australia', 'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Brazil', 'Canada', 'Cape Verde', 'Colombia', 'Croatia', 'Curaçao', 'Czech Republic', 'DR Congo', 'Ecuador', 'Egypt', 'England', 'France', 'Germany', 'Ghana', 'Haiti', 'Iran', 'Iraq', 'Ivory Coast', 'Japan', 'Jordan', 'Mexico', 'Morocco', 'Netherlands', 'New Zealand', 'Norway', 'Panama', 'Paraguay', 'Portugal', 'Qatar', 'Saudi Arabia', 'Scotland', 'Senegal', 'South Africa', 'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Tunisia', 'Turkey', 'United States', 'Uruguay', 'Uzbekistan']

In [20]:
# Both teams must be participants
both_wc_teams = df['home_team'].isin(WC2026_TEAMS) & df['away_team'].isin(WC2026_TEAMS)

# WC 2026 games is what we use as the test set
is_wc2026 = (df['tournament'] == 'FIFA World Cup') & (df['date'].dt.year == 2026)

train = df[both_wc_teams & ~is_wc2026].copy().sort_values('date').reset_index(drop=True)
test  = df[is_wc2026].copy().sort_values('date').reset_index(drop=True)

print(f'Training set: {len(train):,} matches (all history, WC 2026 teams only)')
print(f'Test set:     {len(test):,} WC 2026 matches')
print(f'Date range of training data: {train["date"].min().date()} → {train["date"].max().date()}')

Training set: 7,527 matches (all history, WC 2026 teams only)
Test set:     72 WC 2026 matches
Date range of training data: 1872-11-30 → 2026-06-09

In [21]:
TODAY = pd.Timestamp(date.today())

def recency_weight(match_date):
    days_ago = (TODAY - match_date).days
    if days_ago <= 365 * 3:
        return 3.0
    elif days_ago <= 365 * 8:
        return 2.0
    else:
        return 1.0

train['weight'] = train['date'].apply(recency_weight)

print('Weight distribution in training set:')
print(train['weight'].value_counts().sort_index())

Weight distribution in training set:
weight
1.0    6604
2.0     560
3.0     363
Name: count, dtype: int64

In [22]:
def head_to_head(team_a, team_b):
    mask = (
        ((train['home_team'] == team_a) & (train['away_team'] == team_b)) |
        ((train['home_team'] == team_b) & (train['away_team'] == team_a))
    )
    return train[mask][['date', 'home_team', 'away_team', 'home_score',
                         'away_score', 'tournament', 'winner', 'weight']]

h2h = head_to_head('Brazil', 'Mexico')
print(f'Brazil vs Mexico — all time (training): {len(h2h)} matches')
h2h

Brazil vs Mexico — all time (training): 42 matches

,date,home_team,away_team,home_score,away_score,tournament,winner,weight
1014,1950-06-24,Brazil,Mexico,4.0,0.0,FIFA World Cup,Brazil,1.0
1072,1952-04-06,Brazil,Mexico,2.0,0.0,Pan American Championship,Brazil,1.0
1161,1954-06-16,Brazil,Mexico,5.0,0.0,FIFA World Cup,Brazil,1.0
1229,1956-03-08,Mexico,Brazil,1.0,2.0,Pan American Championship,Brazil,1.0
1411,1960-03-06,Brazil,Mexico,2.0,2.0,Pan American Championship,Draw,1.0
1414,1960-03-15,Brazil,Mexico,2.0,1.0,Pan American Championship,Brazil,1.0
1524,1962-05-30,Brazil,Mexico,2.0,0.0,FIFA World Cup,Brazil,1.0
1814,1968-07-07,Mexico,Brazil,0.0,2.0,Friendly,Brazil,1.0
1815,1968-07-10,Mexico,Brazil,2.0,1.0,Friendly,Mexico,1.0
1833,1968-10-31,Brazil,Mexico,1.0,2.0,Friendly,Mexico,1.0
1835,1968-11-03,Brazil,Mexico,2.0,1.0,Friendly,Brazil,1.0
1946,1970-09-30,Brazil,Mexico,2.0,1.0,Friendly,Brazil,1.0
2153,1974-03-31,Brazil,Mexico,1.0,1.0,Friendly,Draw,1.0
2295,1976-06-04,Mexico,Brazil,0.0,3.0,Friendly,Brazil,1.0
2544,1980-06-08,Brazil,Mexico,2.0,0.0,Friendly,Brazil,1.0
3344,1990-12-12,Mexico,Brazil,0.0,0.0,Friendly,Draw,1.0
3469,1992-07-31,Brazil,Mexico,5.0,0.0,Friendly,Brazil,1.0
3583,1993-08-08,Brazil,Mexico,1.0,1.0,Friendly,Draw,1.0
3624,1993-12-16,Mexico,Brazil,0.0,1.0,Friendly,Brazil,1.0
3835,1996-01-21,Mexico,Brazil,2.0,0.0,Gold Cup,Mexico,1.0
3971,1997-04-30,Brazil,Mexico,4.0,0.0,Friendly,Brazil,1.0
3996,1997-06-16,Brazil,Mexico,3.0,2.0,Copa América,Brazil,1.0
4058,1997-12-16,Brazil,Mexico,3.0,2.0,Confederations Cup,Brazil,1.0
4233,1999-07-03,Brazil,Mexico,2.0,1.0,Copa América,Brazil,1.0
4242,1999-07-14,Mexico,Brazil,0.0,2.0,Copa América,Brazil,1.0
4257,1999-08-04,Mexico,Brazil,4.0,3.0,Confederations Cup,Mexico,1.0
4459,2001-03-07,Mexico,Brazil,3.0,3.0,Friendly,Draw,1.0
4514,2001-07-12,Brazil,Mexico,0.0,1.0,Copa América,Mexico,1.0
4726,2003-04-30,Mexico,Brazil,0.0,0.0,Friendly,Draw,1.0
4760,2003-07-13,Mexico,Brazil,1.0,0.0,Gold Cup,Mexico,1.0
4764,2003-07-27,Mexico,Brazil,1.0,0.0,Gold Cup,Mexico,1.0
4892,2004-07-18,Mexico,Brazil,0.0,4.0,Copa América,Brazil,1.0
5002,2005-06-19,Mexico,Brazil,1.0,0.0,Confederations Cup,Mexico,1.0
5263,2007-06-27,Brazil,Mexico,0.0,2.0,Copa América,Mexico,1.0
5309,2007-09-12,Mexico,Brazil,1.0,3.0,Friendly,Brazil,1.0
5818,2011-10-11,Mexico,Brazil,1.0,2.0,Friendly,Brazil,1.0
5867,2012-06-03,Mexico,Brazil,2.0,0.0,Friendly,Mexico,1.0
6004,2013-06-19,Brazil,Mexico,2.0,0.0,Confederations Cup,Brazil,1.0
6127,2014-06-17,Brazil,Mexico,0.0,0.0,FIFA World Cup,Draw,1.0
6262,2015-06-07,Brazil,Mexico,2.0,0.0,Friendly,Brazil,1.0
6609,2018-07-02,Brazil,Mexico,2.0,0.0,FIFA World Cup,Brazil,2.0
7270,2024-06-08,Mexico,Brazil,2.0,3.0,Friendly,Brazil,3.0